2023-06-15 13:49:03.751 | DEBUG    | utils.cal_testlog:<module>:12 - This is debug information
2023-06-15 13:49:03.752 | INFO     | utils.cal_testlog:<module>:13 - This is info information
2023-06-15 13:49:03.752 | WARNING  | utils.cal_testlog:<module>:14 - This is warn information
2023-06-15 13:49:03.753 | ERROR    | utils.cal_testlog:<module>:15 - This is error information
2023-06-15 13:49:23.395 | ERROR    | _pytest.python:pytest_pyfunc_call:183 - An error has been caught in function 'pytest_pyfunc_call', process 'MainProcess' (29276), thread 'MainThread' (22828):
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\Scripts\pytest-script.py", line 10, in <module>
    sys.exit(console_main())
    │   │    └ <function console_main at 0x00000239486F5040>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
           └ <function main at 0x00000239486EFF70>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
         │     │                │      │    └ <_HookCaller 'pytest_cmdline_main'>
         │     │                │      └ <pluggy.hooks._HookRelay object at 0x000002394A5075E0>
         │     │                └ <_pytest.config.Config object at 0x000002394A480880>
         │     └ <enum 'ExitCode'>
         └ typing.Union

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'config': <_pytest.config.Config object at 0x000002394A480880>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x000002394861F670>
           │    │         │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>>
           └ <_HookCaller 'pytest_cmdline_main'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'config': <_pytest.config.Config object at 0x000002394A480880>}
           │    │               │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
           │    │               └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x000002394799F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000023948614A60>
                                  │     │        │       └ <_HookCaller 'pytest_cmdline_main'>
                                  │     │        └ {'config': <_pytest.config.Config object at 0x000002394A480880>}
                                  │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
                                  └ <_HookCaller 'pytest_cmdline_main'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x000002394A480880>]
          │         └ <function pytest_cmdline_main at 0x00000239487B1430>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\ma...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x00000239487B14C0>
           │            └ <_pytest.config.Config object at 0x000002394A480880>
           └ <function wrap_session at 0x00000239487B13A0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>
    │       │            │    └ <_pytest.config.Config object at 0x000002394A480880>
    │       │            └ <function _main at 0x00000239487B14C0>
    │       └ <ExitCode.OK: 0>
    └ <Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy.hooks._HookRelay object at 0x000002394A5075E0>
    └ <_pytest.config.Config object at 0x000002394A480880>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'session': <Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x000002394861F670>
           │    │         │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>>
           └ <_HookCaller 'pytest_runtestloop'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'session': <Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>}
           │    │               │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
           │    │               └ <_HookCaller 'pytest_runtestloop'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x000002394799F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000023948614A60>
                                  │     │        │       └ <_HookCaller 'pytest_runtestloop'>
                                  │     │        └ {'session': <Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>}
                                  │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
                                  └ <_HookCaller 'pytest_runtestloop'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session My_Codes_V1 exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=4>]
          │         └ <function pytest_runtestloop at 0x00000239487B15E0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\ma...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ None
    │    │                                        └ <Function test_add[0-2-4]>
    │    └ <member 'config' of 'Node' objects>
    └ <Function test_add[0-2-4]>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'item': <Function test_add[0-2-4]>, 'nextitem': None}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x000002394861F670>
           │    │         │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>>
           └ <_HookCaller 'pytest_runtest_protocol'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'item': <Function test_add[0-2-4]>, 'nextitem': None}
           │    │               │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
           │    │               └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x000002394799F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000023948614A60>
                                  │     │        │       └ <_HookCaller 'pytest_runtest_protocol'>
                                  │     │        └ {'item': <Function test_add[0-2-4]>, 'nextitem': None}
                                  │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
                                  └ <_HookCaller 'pytest_runtest_protocol'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_add[0-2-4]>, None]
          │         └ <function pytest_runtest_protocol at 0x00000239487A7E50>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ None
    │               └ <Function test_add[0-2-4]>
    └ <function runtestprotocol at 0x00000239487A7EE0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Function test_add[0-2-4]>
    │       │      └ <function call_and_report at 0x00000239487AA310>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'testcases/test_cal_page.py::TestCal::test_add[0-2-4]' when='setup' outcome='passed'>]

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_add[0-2-4]>
           └ <function call_runtest_hook at 0x00000239487AA430>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod object at 0x00000239487A4850>
           └ <class '_pytest.runner.CallInfo'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x000002394C816280>
            │        └ +TResult
            └ typing.Optional

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_add[0-2-4]>
            └ <_HookCaller 'pytest_runtest_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'item': <Function test_add[0-2-4]>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x000002394861F670>
           │    │         │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>>
           └ <_HookCaller 'pytest_runtest_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'item': <Function test_add[0-2-4]>}
           │    │               │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
           │    │               └ <_HookCaller 'pytest_runtest_call'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x000002394799F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000023948614A60>
                                  │     │        │       └ <_HookCaller 'pytest_runtest_call'>
                                  │     │        └ {'item': <Function test_add[0-2-4]>}
                                  │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
                                  └ <_HookCaller 'pytest_runtest_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_add[0-2-4]>]
          │         └ <function pytest_runtest_call at 0x00000239487AA0D0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x0000023949FFD3A0>
    └ <Function test_add[0-2-4]>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_add[0-2-4]>
    │    └ <property object at 0x0000023948711E50>
    └ <Function test_add[0-2-4]>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'pyfuncitem': <Function test_add[0-2-4]>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x000002394861F670>
           │    │         │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>>
           └ <_HookCaller 'pytest_pyfunc_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'pyfuncitem': <Function test_add[0-2-4]>}
           │    │               │     └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
           │    │               └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x000002394799F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000023947E54AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000023948614A60>
                                  │     │        │       └ <_HookCaller 'pytest_pyfunc_call'>
                                  │     │        └ {'pyfuncitem': <Function test_add[0-2-4]>}
                                  │     └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
                                  └ <_HookCaller 'pytest_pyfunc_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_add[0-2-4]>]
          │         └ <function pytest_pyfunc_call at 0x0000023949FE7A60>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest...

> File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'a': 0, 'b': 2, 'expect': 4}
             └ <bound method TestCal.test_add of <testcases.test_cal_page.TestCal object at 0x000002394C66A310>>

  File "D:\Git_Reps\SoftTest\Soft_test\SoftTest\B01_66 作品\14 UI自动化测试\14.2 网页计算器自动化测试\My_Codes_V1\testcases\test_cal_page.py", line 27, in test_add
    assert add_res == str(expect)
           │              └ 4
           └ '2'

AssertionError: assert '2' == '4'
  - 4
  + 2
