2023-06-20 14:10:52.998 | ERROR    | _pytest.python:pytest_pyfunc_call:183 - An error has been caught in function 'pytest_pyfunc_call', process 'MainProcess' (49216), thread 'MainThread' (45592):
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\Scripts\pytest-script.py", line 10, in <module>
    sys.exit(console_main())
    │   │    └ <function console_main at 0x0000020E0C885040>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
           └ <function main at 0x0000020E0C87FF70>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
         │     │                │      │    └ <_HookCaller 'pytest_cmdline_main'>
         │     │                │      └ <pluggy.hooks._HookRelay object at 0x0000020E0E6975E0>
         │     │                └ <_pytest.config.Config object at 0x0000020E0E210880>
         │     └ <enum 'ExitCode'>
         └ typing.Union

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'config': <_pytest.config.Config object at 0x0000020E0E210880>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x0000020E0C7AF670>
           │    │         │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>>
           └ <_HookCaller 'pytest_cmdline_main'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'config': <_pytest.config.Config object at 0x0000020E0E210880>}
           │    │               │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
           │    │               └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x0000020E0BB2F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000020E0C7A4A60>
                                  │     │        │       └ <_HookCaller 'pytest_cmdline_main'>
                                  │     │        └ {'config': <_pytest.config.Config object at 0x0000020E0E210880>}
                                  │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
                                  └ <_HookCaller 'pytest_cmdline_main'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x0000020E0E210880>]
          │         └ <function pytest_cmdline_main at 0x0000020E0C941430>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\ma...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x0000020E0C9414C0>
           │            └ <_pytest.config.Config object at 0x0000020E0E210880>
           └ <function wrap_session at 0x0000020E0C9413A0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>
    │       │            │    └ <_pytest.config.Config object at 0x0000020E0E210880>
    │       │            └ <function _main at 0x0000020E0C9414C0>
    │       └ <ExitCode.OK: 0>
    └ <Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy.hooks._HookRelay object at 0x0000020E0E6975E0>
    └ <_pytest.config.Config object at 0x0000020E0E210880>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'session': <Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x0000020E0C7AF670>
           │    │         │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>>
           └ <_HookCaller 'pytest_runtestloop'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'session': <Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>}
           │    │               │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
           │    │               └ <_HookCaller 'pytest_runtestloop'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x0000020E0BB2F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000020E0C7A4A60>
                                  │     │        │       └ <_HookCaller 'pytest_runtestloop'>
                                  │     │        └ {'session': <Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>}
                                  │     └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\m...
                                  └ <_HookCaller 'pytest_runtestloop'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session IHRM exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=13>]
          │         └ <function pytest_runtestloop at 0x0000020E0C9415E0>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest\\ma...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ <Function test01_login[case012 \u9519\u8bef\u53c2\u6570-\u624b\u673a\u53f7-login_data11-200-False-20001-\u7528\u6237\u540d\u6...
    │    │                                        └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>
    │    └ <member 'config' of 'Node' objects>
    └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'item': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]...
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x0000020E0C7AF670>
           │    │         │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>>
           └ <_HookCaller 'pytest_runtest_protocol'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'item': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]...
           │    │               │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
           │    │               └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x0000020E0BB2F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000020E0C7A4A60>
                                  │     │        │       └ <_HookCaller 'pytest_runtest_protocol'>
                                  │     │        └ {'item': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]...
                                  │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
                                  └ <_HookCaller 'pytest_runtest_protocol'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>, <Func...
          │         └ <function pytest_runtest_protocol at 0x0000020E0C937E50>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ <Function test01_login[case012 \u9519\u8bef\u53c2\u6570-\u624b\u673a\u53f7-login_data11-200-False-20001-\u7528\u6237\u540d\u6...
    │               └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>
    └ <function runtestprotocol at 0x0000020E0C937EE0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>
    │       │      └ <function call_and_report at 0x0000020E0C93A310>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'testcases/test_login.py::TestLogin::test01_login[case011 \\u65e0\\u53c2-login_data10-200-False-99999-\\u62b1\\u...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>
           └ <function call_runtest_hook at 0x0000020E0C93A430>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod object at 0x0000020E0C934850>
           └ <class '_pytest.runner.CallInfo'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x0000020E10034310>
            │        └ +TResult
            └ typing.Optional

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>
            └ <_HookCaller 'pytest_runtest_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'item': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>}
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x0000020E0C7AF670>
           │    │         │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>>
           └ <_HookCaller 'pytest_runtest_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'item': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>}
           │    │               │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
           │    │               └ <_HookCaller 'pytest_runtest_call'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x0000020E0BB2F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000020E0C7A4A60>
                                  │     │        │       └ <_HookCaller 'pytest_runtest_call'>
                                  │     │        └ {'item': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>}
                                  │     └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
                                  └ <_HookCaller 'pytest_runtest_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>]
          │         └ <function pytest_runtest_call at 0x0000020E0C93A0D0>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest...

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x0000020E0E18D3A0>
    └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>

  File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>
    │    └ <property object at 0x0000020E0C8A70E0>
    └ <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
           │    │         │     │    │                └ {'pyfuncitem': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\...
           │    │         │     │    └ <function _HookCaller.get_hookimpls at 0x0000020E0C7AF670>
           │    │         │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>>
           └ <_HookCaller 'pytest_pyfunc_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
           │    │               │     │        └ {'pyfuncitem': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\...
           │    │               │     └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
           │    │               └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <function PluginManager.__init__.<locals>.<lambda> at 0x0000020E0BB2F040>
           └ <_pytest.config.PytestPluginManager object at 0x0000020E0BFE4AF0>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
                                  │     │        │       │    └ <function _multicall at 0x0000020E0C7A4A60>
                                  │     │        │       └ <_HookCaller 'pytest_pyfunc_call'>
                                  │     │        └ {'pyfuncitem': <Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\...
                                  │     └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytes...
                                  └ <_HookCaller 'pytest_pyfunc_call'>

  File "D:\ProgramData\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test01_login[case011 \u65e0\u53c2-login_data10-200-False-99999-\u62b1\u6b49\uff0c\u7cfb\u7edf\u7e41\u5fd9]>]
          │         └ <function pytest_pyfunc_call at 0x0000020E0E178A60>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\_pytest...

> File "D:\ProgramData\Anaconda3\lib\site-packages\_pytest\python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'desc': 'case011 无参', 'login_data': {}, 'sc': 200, 'suc': False, 'code': 99999, 'msg': '抱歉，系统繁忙'}
             └ <bound method TestLogin.test01_login of <testcases.test_login.TestLogin object at 0x0000020E10024C40>>

  File "D:\Git_Reps\SoftTest\Soft_test\SoftTest\B01_66 作品\07 接口自动化测试\06 接口自动化测试\IHRM\testcases\test_login.py", line 34, in test01_login
    assert code == login_res.json().get("code")
           │       │         └ <function Response.json at 0x0000020E0FCFF1F0>
           │       └ <Response [200]>
           └ 99999

AssertionError: assert 99999 == 20001
 +  where 20001 = <built-in method get of dict object at 0x0000020E1002AB00>('code')
 +    where <built-in method get of dict object at 0x0000020E1002AB00> = {'code': 20001, 'data': None, 'message': '用户名或密码错误', 'success': False}.get
 +      where {'code': 20001, 'data': None, 'message': '用户名或密码错误', 'success': False} = <bound method Response.json of <Response [200]>>()
 +        where <bound method Response.json of <Response [200]>> = <Response [200]>.json
